# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Haywire
email: abhinavagrawal1995@gmail.com
github.url: https://github.com/abhinavagrawal1995/abhinavagrawal1995.github.io
description: > # this means to ignore newlines until "baseurl:"
  Sab kuch Haywire hai
  
  
  
baseurl: "/haywire" # the subpath of your site, e.g. /blog
url: "http://abhinavagrawal.in" # the base hostname & protocol for your site

#sidebar
default-image: typewriter.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
developed-by: Abhinav Agrawal
copyright:
   name: Abhinav Agrawal
   link: 'http://abhinavagrawal.in'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: haywire/page:num/

# Tracker
analytics: UA-52121429-4

# Comments
disqus-shortname: haywire-1

#social
facebook: https://www.facebook.com/abi.agrawal1995
github: http://github.com/abhinavagrawal1995

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]

